version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      # 任意のパスワード
      MYSQL_ROOT_PASSWORD: <<HOGEHOGE>>
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql 

volumes:
  db_data:
    driver: local